### PR TITLE
Updated readme with the following changes

### PR DESCRIPTION
**Pull request by meowyx**
- added missing scripts
- explained how to run with linea by changing directory
- removed zk-vote mentions
- removed `.env` mentions

### CODE REVIEW

**Comment by meowyx** [comment]
added `.env` back

**Review by cxalem — APPROVED** [review]
This looks pretty good!!!

**Review by cxalem — CHANGES_REQUESTED** [review]
Quick fix:

- If they want to run the local network, they will have to deploy a local Contract, and they'll have to update the contract we're calling in cd `apps/web/lib/contracts.ts/config.ts` with the contract they just deployed.

**Comment by meowyx** [comment]
@cxalem made the changes as suggested.

**Pull request merged**
